"""Generate desktop/config.local.json from the running local Supabase stack.

Also writes mobile/lib/config.local.dart with the LAN address so a phone on
the same network can reach the local Supabase instance.

Usage:
    python3 tools/write_supabase_env.py

Generated files are git-ignored. They contain only public client keys; the
service-role key is never written to app config.
"""

import json
import socket
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "desktop" / "config.local.json"
MOBILE_CONFIG_PATH = ROOT / "mobile" / "lib" / "config.local.dart"


def local_ip() -> str:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        sock.connect(("8.8.8.8", 80))
        return sock.getsockname()[0]
    except OSError:
        return "127.0.0.1"
    finally:
        sock.close()


def main() -> int:
    result = subprocess.run(
        ["supabase", "status", "-o", "json"],
        capture_output=True,
        text=True,
        cwd=ROOT,
    )
    if result.returncode != 0:
        print("Could not read `supabase status`. Is the local stack running?")
        print(result.stderr.strip()[:500])
        return 1

    try:
        status = json.loads(result.stdout)
    except json.JSONDecodeError:
        print("Unexpected `supabase status` output; expected JSON.")
        return 1

    api_url = status.get("API_URL")
    anon_key = status.get("ANON_KEY")
    if not api_url or not anon_key:
        print("API_URL or ANON_KEY missing from `supabase status`.")
        return 1

    config = {
        "supabase_url": api_url,
        "supabase_anon_key": anon_key,
        "studio_url": status.get("STUDIO_URL", ""),
        "generated_by": "tools/write_supabase_env.py",
    }
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(config, indent=2) + "\n")
    print(f"Wrote {CONFIG_PATH.relative_to(ROOT)}")
    print(f"  url: {api_url}")

    # Mobile build needs the LAN IP because 127.0.0.1 is the phone itself.
    lan_url = api_url.replace("127.0.0.1", local_ip())
    MOBILE_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    MOBILE_CONFIG_PATH.write_text(
        "// Generated by tools/write_supabase_env.py — do not commit.\n"
        f"const String supabaseUrl = '{lan_url}';\n"
        f"const String supabaseAnonKey = '{anon_key}';\n"
    )
    print(f"Wrote {MOBILE_CONFIG_PATH.relative_to(ROOT)}")
    print(f"  url: {lan_url} (LAN address for phones)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
