"""Generate desktop/mobile/web configs from a Supabase stack.

Default: the running local stack (`supabase start`).
Hosted:  `python3 tools/write_supabase_env.py --hosted` reads
         supabase/.env.hosted (git-ignored) with SUPABASE_URL and
         SUPABASE_ANON_KEY.

Generated files are git-ignored. They contain only public client keys; the
service-role key and database password are never written to app config.
"""

import json
import socket
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "desktop" / "config.local.json"
MOBILE_CONFIG_PATH = ROOT / "mobile" / "lib" / "config.local.dart"
WEB_CONFIG_PATH = ROOT / "admin-web" / ".env.local"
HOSTED_ENV = ROOT / "supabase" / ".env.hosted"


def local_ip() -> str:
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        sock.connect(("8.8.8.8", 80))
        return sock.getsockname()[0]
    except OSError:
        return "127.0.0.1"
    finally:
        sock.close()


def read_hosted() -> tuple[str, str]:
    values: dict[str, str] = {}
    if HOSTED_ENV.exists():
        for line in HOSTED_ENV.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    url = values.get("SUPABASE_URL", "")
    key = values.get("SUPABASE_ANON_KEY", "")
    if not url or not key:
        print("supabase/.env.hosted needs SUPABASE_URL and SUPABASE_ANON_KEY "
              "(dashboard → Project Settings → API).")
        sys.exit(1)
    return url, key


def local_stack() -> tuple[str, str, str]:
    result = subprocess.run(
        ["supabase", "status", "-o", "json"],
        capture_output=True, text=True, cwd=ROOT,
    )
    if result.returncode != 0:
        print("Could not read `supabase status`. Is the local stack running?")
        print(result.stderr.strip()[:300])
        sys.exit(1)
    status = json.loads(result.stdout)
    return status.get("API_URL", ""), status.get("ANON_KEY", ""), status.get("STUDIO_URL", "")


def main() -> int:
    hosted = "--hosted" in sys.argv
    if hosted:
        api_url, anon_key = read_hosted()
        studio_url = ""
        print("Using hosted Supabase from supabase/.env.hosted")
    else:
        api_url, anon_key, studio_url = local_stack()
        if not api_url or not anon_key:
            print("API_URL or ANON_KEY missing from `supabase status`.")
            return 1
        print("Using the local Supabase stack")

    config = {
        "supabase_url": api_url,
        "supabase_anon_key": anon_key,
        "studio_url": studio_url,
        "generated_by": "tools/write_supabase_env.py",
        "hosted": hosted,
    }
    CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_PATH.write_text(json.dumps(config, indent=2) + "\n")
    print(f"Wrote {CONFIG_PATH.relative_to(ROOT)}")
    print(f"  url: {api_url}")

    # Mobile: phones need a LAN-reachable URL only for the local stack.
    mobile_url = api_url
    if not hosted:
        mobile_url = api_url.replace("127.0.0.1", local_ip())
    MOBILE_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    MOBILE_CONFIG_PATH.write_text(
        "// Generated by tools/write_supabase_env.py — do not commit.\n"
        f"const String supabaseUrl = '{mobile_url}';\n"
        f"const String supabaseAnonKey = '{anon_key}';\n"
    )
    print(f"Wrote {MOBILE_CONFIG_PATH.relative_to(ROOT)}")
    print(f"  url: {mobile_url}")

    # Web admin console (Vite reads VITE_* variables).
    WEB_CONFIG_PATH.parent.mkdir(parents=True, exist_ok=True)
    WEB_CONFIG_PATH.write_text(
        f"VITE_SUPABASE_URL={api_url}\n"
        f"VITE_SUPABASE_ANON_KEY={anon_key}\n"
    )
    print(f"Wrote {WEB_CONFIG_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
