"""Desktop configuration loader.

Reads desktop/config.local.json (generated by tools/write_supabase_env.py),
falling back to environment variables. The anon key is a public client key;
the service-role key must never appear here.
"""

import json
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "desktop" / "config.local.json"


def load_config() -> dict:
    config = {
        "supabase_url": os.environ.get("VISIONQC_SUPABASE_URL", ""),
        "supabase_anon_key": os.environ.get("VISIONQC_SUPABASE_ANON_KEY", ""),
        "studio_url": os.environ.get("VISIONQC_STUDIO_URL", ""),
    }
    if CONFIG_PATH.exists():
        file_config = json.loads(CONFIG_PATH.read_text())
        config.update({k: v for k, v in file_config.items() if v})
    return config


def is_configured(config: dict | None = None) -> bool:
    config = config or load_config()
    return bool(config.get("supabase_url") and config.get("supabase_anon_key"))
